# Site Settings
locale: "pt-BR"
title: "Pedro Saliba"
title_separator: "-"
subtitle: "Pesquisador em Direito e Tecnologia"
name: "Pedro Saliba"
description: "Pesquisador em Direito e Tecnologia. Segurança, vigilância e direitos fundamentais."
url: "https://pedrosaliba.com.br"
baseurl: ""
repository: "pedrosaliba/pedrosaliba.github.io"
teaser:
breadcrumbs: false
words_per_minute: 200

# Author
author:
  name: "Pedro Saliba"
  avatar: "/images/bio-photo.jpg"
  bio: "Pesquisador em Direito e Tecnologia"
  location: "Brasil"
  email: "pedrosaliba@proton.me"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:pedrosaliba@proton.me"

# Navigation
navigation:
  - title: "Publicações"
    url: /publicacoes/
  - title: "Palestras"
    url: /palestras/
  - title: "Ensino"
    url: /ensino/
  - title: "Produção de Conteúdo"
    url: /conteudo/
  - title: "Blog"
    url: /blog/
  - title: "CV"
    url: /cv/

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .github
  - Gemfile
  - Gemfile.lock

# Build Settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5
paginate_path: /blog/page:num/
timezone: America/Sao_Paulo

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true